"""empty message

Revision ID: 456c66a42ee9
Revises: ab569a567c36
Create Date: 2020-09-05 19:02:56.245356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456c66a42ee9'
down_revision = 'ab569a567c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
