"""empty message

Revision ID: 926eeb1dfd77
Revises: aadde0bf9690
Create Date: 2020-09-03 18:07:07.726886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926eeb1dfd77'
down_revision = 'aadde0bf9690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('emotion_percent', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('comments', 'emotion_percent')
    # ### end Alembic commands ###
