"""empty message

Revision ID: aadde0bf9690
Revises: 95c68cade41e
Create Date: 2020-09-02 22:35:21.688950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadde0bf9690'
down_revision = '95c68cade41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('movies', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'code')
    # ### end Alembic commands ###
