"""empty message

Revision ID: ab569a567c36
Revises: 926eeb1dfd77
Create Date: 2020-09-05 19:00:44.221443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab569a567c36'
down_revision = '926eeb1dfd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column(
        'pos_or_neg', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('comments', 'pos_or_neg')
    # ### end Alembic commands ###
